### ISSUE TITLE
Not working resizing iframe

### ISSUE THREAD

**Issue by r74tech** [scpwiki/interwiki#22]
Currently, the resize mechanism of the iframe is updated by changing the src of `resize-iframe.html`, but depending on the timing of the update, the height may remain at 0.

As a solution to this problem, after running debounce, I suggest deleting the contents of resizer-container and replacing it with a new `resize-iframe.html`.

https://github.com/RTa-scp/interwiki/blob/494a2cb2d26e60ec018d359775ade523bda6d07c/js/createResizeIframe.js#L24-L47

If it is not allowed for people outside the organization to build issues without permission, it would be appreciated if you could close it.

**Comment by emmiegit** [comment]
cc @Woedenaz @rossjrw
