### ISSUE TITLE
KO translations doesn't show up

### ISSUE THREAD

**Issue by XCninety** [scpwiki/interwiki#28]
We the Korean branch think that it is needed to report a malfunction of Interwiki module again, because it's still broken even after the http issue above is solved.

This is some examples show the issue:
* https://scp-wiki.wikidot.com/scp-329
* https://scpko.wikidot.com/scp-329
* http://scp-jp.wikidot.com/scp-3773-jp
* https://scpko.wikidot.com/scp-3773-jp

As you can see, the Interwiki module list up translations of the article only except KO version.

Not all KO articles are related in this isssue - It seems the Interwiki module can't read the articles which are uploaded on the KO wiki after August 16. And the date is when KO upgraded itself to https.

This report has also been relayed to INT TechTrust.

**Comment by rossjrw** [comment]
Was able to reproduce this via API query to Crom:

```
query {
  page(url: "http://scpko.wikidot.com/scp-329") {
    translations {
      url
    }
    translationOf {
      url
    }
  }
}
```

returns a full list of translations and no translationOf entry, as if SCP-329@KO is the original article; other than EN being included in KO's result, this is identical to the result when querying http://scp-wiki.wikidot.com/scp-329

Tested that same query against SCP-200@KO (translated long enough ago to be known to be working), which correctly returns 0 translations and 1 translationOf

According to listpages, the first KO translation of an EN article after KO switched to HTTPS on the 16th is `/thank-you-for-your-time` on the 17th, which exhibits the same issue as SCP-329. The last KO translation of an EN article before KO switched to HTTPS was `/art:asset-slorp` on the 14th, which is correctly marked as a translation. I think that confirms that HTTPS is causing the issue. I suspect Crom isn't handling it correctly and will report the bug upstream to smlt.

**Comment by rossjrw** [comment]
smlt confirms that the HTTPS switch was causing issues in Crom's crawling of new articles and has fixed it on his end; interwiki is now displaying KO translations correctly.
